// Copyright (c) 2020-2024 Atypical Consulting SRL. All rights reserved.
// Atypical Consulting SRL licenses this file to you under the Apache 2.0 license.
// See the LICENSE file in the project root for full license information.

using ReverseMutty.CodeHelpers;

namespace ReverseMutty.Templates;

/// <summary>
/// A template that generates the mutable generation attribute.
/// </summary>
public class ImmutableGenerationAttributeTemplate : IndentedCodeBuilder
{
    /// <summary>
    /// Generates the code for the mutable generation attribute.
    /// </summary>
    /// <returns>The generated code.</returns>
    public string GenerateCode()
    {
        CommentAutoGenerated();
        Line("namespace ReverseMutty");
        Braces(() =>
        {
            Summary("Indicates that the class can be generated by the ReverseMutty generator.");
            Line("[AttributeUsage(AttributeTargets.Class, Inherited = false)]");
            Line("public class ImmutableGenerationAttribute : Attribute");
            Braces(() =>
            {
                // Empty constructor
                Summary("Initializes a new instance of the <see cref=\"ImmutableGenerationAttribute\" /> class.");
                Line("public ImmutableGenerationAttribute() { }");
            });
        });

        return ToString();
    }
}
